### ISSUE TITLE
Dimmable light reports max 254% in gateway UI

### ISSUE THREAD

**Issue by fillier** [mozilla-iot/philips-hue-adapter#12]
Gateway UI shows Hue bulbs @ 254% when set to full brightness. When trying to set brightness the UI only allows setting to 100% which in reality is only about half brightness. Intercepting the properties/level PUT and overriding the value to 254 will set the bulb to full brightness.

**Comment by hobinjk** [comment]
Sorry for the inconvenience! There's a missing conversion between the UI's level (0-100) and the Hue API's level (0-254) in the adapter. I'll fix this ASAP

**Comment by fillier** [comment]
Yep, I saw that in the code. Love to implement a fix but I'm unsure how to test...copied fixed file to my pi but startup complained about failed checksum on the addon. Are there any docs on how to test addons locally?

**Comment by hobinjk** [comment]
This should be fixed in the 0.4.3 release. With the current version of the gateway you'll need to uninstall the 0.4.2 version of the adapter and reinstall the 0.4.3 version (or continue using your locally modified version). Thanks for the contribution!
