### ISSUE TITLE
RGB light doesn't have brightness property

### ISSUE THREAD

**Issue by svrooij** [mozilla-iot/philips-hue-adapter#22]
I got several RGB lights around the house. They showup nicely but they don't have a brightness control in the interface. While other lights that don't have color do have a brightness control thing

**Comment by mrstegeman** [comment]
@svrooij Brightness is actually a component of the color, as most lights implement an HSL (hue, saturation, lightness) color space. For the color picker, we default to the native implementation, but on most systems, that picker will include a brightness slider.
