### ISSUE TITLE
Feature detect white-only bulbs

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/philips-hue-adapter#3]
This will require my buying a philips hue white bulb and seeing what it does in the API

**Comment by NielsLeenheer** [comment]
There are multiple types of white lights that can be connected to a Hue bridge. Lights that can only be turned on and off, lights with brightness control and lights with color temperature control. Additionally, it is possible to pair a switch to the hue, which is exposed as a lightbulb with just on/off.

All lights connected to the Hue bridge are either one of these types:

Type | Properties
-- | --
Extended color light | on, bri, ct, xy, hue, sat
Color light | on, bri, ct, xy, hue, sat
Color temperature light | on, bri, ct
Dimmable light | on, bri
On/Off light | on
