### ISSUE TITLE
Motion sensor lacks of lightlevel and dark property

### ISSUE THREAD

**Issue by tim-hellhake** [mozilla-iot/philips-hue-adapter#43]
The motion sensor delivers 3 values: `lightlevel`, `dark` and `daylight`.
Currently only `daylight` is exposed as property.

**Comment by freaktechnik** [comment]
I believe this is a dupe of https://github.com/mozilla-iot/philips-hue-adapter/issues/25 btw. All the values are exposed, they are just exposed as three things.
