### ISSUE TITLE
Support CIE xy mode for color bulbs

### ISSUE THREAD

**Issue by NielsLeenheer** [mozilla-iot/philips-hue-adapter#5]
Not every lightbulb will support the same color gamut. Using hue and saturation is hardware dependent and the same values may result in different colors – even if all bulbs are capable of actually showing that color. 

CIE xy mode is supposed to be hardware independent. That means that the same value will result in the same color – at least if the color is in within the gamut that the lightbulb supports. If not, it will show the closest color possible.

**Comment by hobinjk** [comment]
The way this adapter handles color is specified by the web thing api specification in https://github.com/mozilla-iot/wot. Currently color is defined as a CSS color string but using CIE xy/xyY does sound like an interesting way to specify them. I've filed [an issue on the WoT repo](https://github.com/mozilla-iot/wot/issues/52) to track exploring better color representations.

**Comment by NielsLeenheer** [comment]
I'm not sure that supporting CIE xy in the spec is required. 

Right now the CSS color is translated to hue, saturation and brightness. Instead translating the CSS color to CIE xy already achieves the goal of showing consistent colors on bulbs with different gamuts. Only if a color is outside of the gamut colors will diverge.

**Comment by NielsLeenheer** [comment]
BTW, the Hue developer site has the right conversion algorithm for converting RGB to XY:
https://developers.meethue.com/documentation/color-conversions-rgb-xy

**Comment by hobinjk** [comment]
Oh, I see what you mean. Sorry for misunderstanding!
